version: 1.0.{build}
clone_folder: C:\Go\src\github.com\carolynvs\magic
environment:
  GOPATH: C:\Go
  CHOCO_APIKEY:
    secure: X8dN8VATxHQAHxbwawEpCov4SaerAp45Uqc8dDlM9b4=
build_script:
- ps: >-
    $ErrorActionPreference = "Stop";
    $env:PATH+="$env:PATH;$GOPATH\bin";
    bash -c "./build.sh";
    installer\publish.ps1 -version $env:APPVEYOR_BUILD_VERSION -apikey $env:CHOCO_APIKEY
